import { useEffect, useRef, useState } from 'react'
import { createPeer, type PeerHandle, type PeerState } from '../phone/peer'
import type { PhoneMessage } from '../phone/wire'
import { loadSettings } from '../store/settings'

interface PairScreenProps {
  onClose: () => void
}

/**
 * Phase 2b.1 — laptop-side pairing UI. Manual SDP copy/paste.
 *
 * Intentional throwaway UX (decision memo §"Throwaway scaffolding"): the
 * two-textarea flow ships only to prove the WebRTC DataChannel transport.
 * Phase 2b.2 replaces this with QR scanning; the only parts that survive
 * past 2b.1 are `phone/peer.ts`, `phone/wire.ts`, and the `/phone` route.
 */
export function PairScreen({ onClose }: PairScreenProps) {
  const peerRef = useRef<PeerHandle | null>(null)
  const [state, setState] = useState<PeerState>('idle')
  const [offerText, setOfferText] = useState('')
  const [answerText, setAnswerText] = useState('')
  const [phoneUrl, setPhoneUrl] = useState<string | null>(null)
  const [err, setErr] = useState<string | null>(null)
  const [startedAt, setStartedAt] = useState<number | null>(null)
  const [lastCommit, setLastCommit] = useState<{
    receivedAt: number
    sentAt: number
  } | null>(null)

  useEffect(() => {
    let cancelled = false
    void loadSettings().then((s) => {
      if (cancelled) return
      const ip = s.laptopLanIp?.trim()
      // window.location.port is always present when the SPA itself is loaded
      // (the laptop is reading this page); the URL we render is whatever
      // origin served us, so the phone hits the same port.
      const port = window.location.port
      if (ip) setPhoneUrl(`http://${ip}:${port}/phone`)
    })
    return () => {
      cancelled = true
      peerRef.current?.close()
    }
  }, [])

  async function handleGenerateOffer(): Promise<void> {
    setErr(null)
    if (peerRef.current) {
      setErr('Already generated an offer — reload to start over.')
      return
    }
    try {
      const peer = createPeer()
      peerRef.current = peer
      peer.onStateChange(setState)
      peer.onMessage((m: PhoneMessage) => {
        if (m.type === 'commit') {
          setLastCommit({ receivedAt: Date.now(), sentAt: m.t })
        }
      })
      setStartedAt(Date.now())
      const offer = await peer.createOffer()
      setOfferText(offer)
    } catch (e) {
      setErr(e instanceof Error ? e.message : String(e))
    }
  }

  async function handleAcceptAnswer(): Promise<void> {
    setErr(null)
    const peer = peerRef.current
    if (!peer) {
      setErr('Generate an offer first.')
      return
    }
    if (!answerText.trim()) {
      setErr('Paste the answer SDP from the phone.')
      return
    }
    try {
      await peer.acceptAnswer(answerText)
    } catch (e) {
      setErr(e instanceof Error ? e.message : String(e))
    }
  }

  const sinceStart =
    startedAt !== null && lastCommit
      ? lastCommit.receivedAt - startedAt
      : null

  return (
    <div className="screen pair-screen">
      <header className="settings-header">
        <h1>Pair phone (Phase 2b.1)</h1>
        <button type="button" className="link" onClick={onClose}>
          Close
        </button>
      </header>

      <p className="hint">
        Manual SDP pairing — temporary scaffolding. Phase 2b.2 replaces this
        with QR scanning.
      </p>

      <section className="settings-section">
        <h2>1. Open the phone companion page</h2>
        {phoneUrl ? (
          <p>
            On your phone, open <code data-testid="phone-url">{phoneUrl}</code>.
          </p>
        ) : (
          <p className="hint">
            Set your laptop's LAN IP in Settings to see the phone URL here.
          </p>
        )}
      </section>

      <section className="settings-section">
        <h2>2. Generate an offer</h2>
        <button
          type="button"
          className="primary"
          onClick={() => void handleGenerateOffer()}
          disabled={state !== 'idle' && state !== 'error'}
        >
          Generate offer
        </button>
        <textarea
          aria-label="offer SDP"
          rows={6}
          value={offerText}
          readOnly
          placeholder="(generated by clicking Generate offer)"
        />
        <p className="hint">Copy this whole block onto the phone screen.</p>
      </section>

      <section className="settings-section">
        <h2>3. Paste the phone's answer</h2>
        <textarea
          aria-label="answer SDP"
          rows={6}
          value={answerText}
          onChange={(e) => setAnswerText(e.target.value)}
          placeholder="v=0…"
        />
        <button
          type="button"
          className="primary"
          onClick={() => void handleAcceptAnswer()}
          disabled={state !== 'awaiting_answer'}
        >
          Connect
        </button>
      </section>

      <section className="settings-section">
        <h2>4. Status</h2>
        <p>
          Connection: <strong data-testid="pair-state">{state}</strong>
        </p>
        {lastCommit && (
          <p data-testid="last-commit">
            Last commit received at +{sinceStart}ms (phone clock t=
            {lastCommit.sentAt}).
          </p>
        )}
      </section>

      {err && (
        <div className="banner warn" role="alert">
          {err}
        </div>
      )}
    </div>
  )
}
